extends TextureRect

var Cplus = {
	0: preload("res://Art/Other/Study/C++/c0.png"),
	1: preload("res://Art/Other/Study/C++/c1.png"),
	2: preload("res://Art/Other/Study/C++/c2.png"),
	3: preload("res://Art/Other/Study/C++/c3.png"),
	4: preload("res://Art/Other/Study/C++/c4.png"),
	5: preload("res://Art/Other/Study/C++/c5.png"),
	6: preload("res://Art/Other/Study/C++/c6.png"),
	7: preload("res://Art/Other/Study/C++/c7.png"),
	8: preload("res://Art/Other/Study/C++/c8.png"),
	9: preload("res://Art/Other/Study/C++/c9.png"),
	10: preload("res://Art/Other/Study/C++/c10.png"),
	11: preload("res://Art/Other/Study/C++/c11.png"),
	12: preload("res://Art/Other/Study/C++/c12.png"),
	13: preload("res://Art/Other/Study/C++/c13.png"),
	14: preload("res://Art/Other/Study/C++/c14.png"),
	15: preload("res://Art/Other/Study/C++/c15.png"),
	16: preload("res://Art/Other/Study/C++/c16.png"),
	17: preload("res://Art/Other/Study/C++/c17.png"),
	18: preload("res://Art/Other/Study/C++/c18.png"),
	19: preload("res://Art/Other/Study/C++/c19.png"),
	20: preload("res://Art/Other/Study/C++/c20.png"),
	21: preload("res://Art/Other/Study/C++/c21.png"),
	22: preload("res://Art/Other/Study/C++/c22.png"),
	23: preload("res://Art/Other/Study/C++/c23.png"),
	24: preload("res://Art/Other/Study/C++/c24.png"),
	25: preload("res://Art/Other/Study/C++/c25.png"),
	26: preload("res://Art/Other/Study/C++/c26.png"),
	27: preload("res://Art/Other/Study/C++/c27.png"),
	28: preload("res://Art/Other/Study/C++/c28.png"),
	29: preload("res://Art/Other/Study/C++/c29.png"),
	30: preload("res://Art/Other/Study/C++/c30.png"),
	31: preload("res://Art/Other/Study/C++/c31.png"),
	32: preload("res://Art/Other/Study/C++/c32.png"),
	33: preload("res://Art/Other/Study/C++/c33.png"),
	34: preload("res://Art/Other/Study/C++/c34.png"),
	35: preload("res://Art/Other/Study/C++/c35.png"),
	-1: preload("res://Art/Other/Study/C++/cq1.png"),
	-2: preload("res://Art/Other/Study/C++/cq2.png"),
	-3: preload("res://Art/Other/Study/C++/cq3.png"),
	-4: preload("res://Art/Other/Study/C++/cq4.png"),
	36: preload("res://Art/Other/Study/C++/c36.png"),
	37: preload("res://Art/Other/Study/C++/c37.png"),
	38: preload("res://Art/Other/Study/C++/c38.png"),
	39: preload("res://Art/Other/Study/C++/c39.png"),
	40: preload("res://Art/Other/Study/C++/c40.png"),
	41: preload("res://Art/Other/Study/C++/c41.png"),
	42: preload("res://Art/Other/Study/C++/c42.png"),
	43: preload("res://Art/Other/Study/C++/c43.png"),
	44: preload("res://Art/Other/Study/C++/c44.png"),
}

func _process(delta):
	self.texture = Cplus[Game.CPlusLesson]
