extends TextureRect

var CSS = {
	0: preload("res://Art/Other/Study/Css/css0.png"),
	1: preload("res://Art/Other/Study/Css/css1.png"),
	2: preload("res://Art/Other/Study/Css/css2.png"),
	3: preload("res://Art/Other/Study/Css/css3.png"),
	4: preload("res://Art/Other/Study/Css/css4.png"),
	5: preload("res://Art/Other/Study/Css/css5.png"),
	6: preload("res://Art/Other/Study/Css/css6.png"),
	7: preload("res://Art/Other/Study/Css/css7.png"),
	8: preload("res://Art/Other/Study/Css/css8.png"),
	9: preload("res://Art/Other/Study/Css/css9.png"),
	10: preload("res://Art/Other/Study/Css/css10.png"),
	11: preload("res://Art/Other/Study/Css/css11.png"),
	12: preload("res://Art/Other/Study/Css/css12.png"),
	13: preload("res://Art/Other/Study/Css/css13.png"),
	14: preload("res://Art/Other/Study/Css/css14.png"),
	15: preload("res://Art/Other/Study/Css/css15.png"),
	16: preload("res://Art/Other/Study/Css/css16.png"),
	17: preload("res://Art/Other/Study/Css/css17.png"),
	18: preload("res://Art/Other/Study/Css/css18.png"),
	19: preload("res://Art/Other/Study/Css/css19.png"),
	20: preload("res://Art/Other/Study/Css/css20.png"),
	21: preload("res://Art/Other/Study/Css/css21.png"),
	22: preload("res://Art/Other/Study/Css/css22.png"),
	23: preload("res://Art/Other/Study/Css/css23.png"),
	24: preload("res://Art/Other/Study/Css/css24.png"),
	25: preload("res://Art/Other/Study/Css/css25.png"),
	26: preload("res://Art/Other/Study/Css/css26.png"),
	27: preload("res://Art/Other/Study/Css/css27.png"),
	28: preload("res://Art/Other/Study/Css/css28.png"),
	29: preload("res://Art/Other/Study/Css/css29.png"),
	30: preload("res://Art/Other/Study/Css/css30.png"),
	31: preload("res://Art/Other/Study/Css/css31.png"),
	32: preload("res://Art/Other/Study/Css/css32.png"),
	33: preload("res://Art/Other/Study/Css/css33.png"),
	34: preload("res://Art/Other/Study/Css/css34.png"),
	35: preload("res://Art/Other/Study/Css/css35.png"),
	36: preload("res://Art/Other/Study/Css/css36.png"),
	37: preload("res://Art/Other/Study/Css/css37.png"),
}
func _process(delta):
	self.texture = CSS[Game.CssLesson]
